//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanDongHo60135761.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CTHDB
    {
        public int MaHD { get; set; }
        [Required(ErrorMessage = "Nhập số lượng.")]
        [Range(1, Int32.MaxValue, ErrorMessage = "Số lượng ít nhất phải là {1}.")]
        public Nullable<int> SoLuong { get; set; }
        [Required(ErrorMessage = "Nhập giá bán.")]
        [Range(1000000, Int32.MaxValue, ErrorMessage = "Đơn giá ít nhất phải là {1:#,##0} đồng")]
        public int DonGia { get; set; }
        public string MaDH { get; set; }
    
        public virtual DongHo DongHo { get; set; }
        public virtual HoaDonBan HoaDonBan { get; set; }
    }
}
