//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanDongHo60135761.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DongHo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DongHo()
        {
            this.CTHDBs = new HashSet<CTHDB>();
        }
        [Required(ErrorMessage = "Nhập mã đồng hồ.")]
        public string MaDH { get; set; }
        [Required(ErrorMessage ="Nhập tên đồng hồ.")]
        public string TenDongHo { get; set; }
        public string AnhSanPham { get; set; }
        [Required(ErrorMessage = "Nhập giá bán.")]
        [Range(1000000, Int32.MaxValue, ErrorMessage = "Giá bán ít nhất là {1:#,##0} đồng")]
        [DisplayFormat(DataFormatString = "{0:#,##0 đồng}", ApplyFormatInEditMode = false)]
        public int GiaBan { get; set; }
        public string Mota { get; set; }
        public string GhiChu { get; set; }
        public string MaLoaiDH { get; set; }
        public string MaNCC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHDB> CTHDBs { get; set; }
        public virtual LoaiDongHo LoaiDongHo { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
