//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanDongHo60135761.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HoaDonBan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDonBan()
        {
            this.CTHDBs = new HashSet<CTHDB>();
        }
    
        public int MaHD { get; set; }
        [Required(ErrorMessage = "Nhập ngày đặt hàng.")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime NgayDatHang { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Nhập ngày giao hàng.")]
        public System.DateTime NgayGiaoHang { get; set; }
        [Required(ErrorMessage = "Nhập tên người nhận.")]
        public string TenNguoiNhan { get; set; }
        [Required(ErrorMessage = "Nhập số điện thoại người nhận.")]
        [MinLength(10, ErrorMessage = "Nhập số điện thoại gồm 10 chữ số.")]
        public string SDTNguoiNhan { get; set; }
        [Required(ErrorMessage = "Nhập địa chỉ nhận hàng.")]
        public string DiaChiNhanHang { get; set; }
        [Required(ErrorMessage = "Nhập tình trạng hoá đơn.")]
        public string TinhTrangHoaDon { get; set; }
        [Required(ErrorMessage = "Nhập hình thức thanh toán.")]
        public string HinhThucThanhToan { get; set; }
        public string MaNV { get; set; }
        public Nullable<int> MaKH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHDB> CTHDBs { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
