//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanDongHo60135761.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.HoaDonBans = new HashSet<HoaDonBan>();
        }
    
        public int MaKH { get; set; }
        [Required(ErrorMessage = "Nhập họ và tên.")]
        public string HoTenKH { get; set; }
        public bool GioiTinhKH { get; set; }
        [Required(ErrorMessage = "Nhập địa chỉ.")]
        public string DiaChiKH { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        
        [Required(ErrorMessage = "Nhập ngày sinh.")]
        public System.DateTime NgaySinhKH { get; set; }
        [Required(ErrorMessage = "Nhập số điện thoại.")]
        [MinLength(10, ErrorMessage = "Nhập số điện thoại gồm 10 chữ số.")]
        public string SoDTKH { get; set; }
        [Required(ErrorMessage = "Nhập email.")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Nhập đúng định dạng email.")]
        [StringLength(30, ErrorMessage = "Email được phép nhập tối đa 30 kí tự.")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Nhập tên đăng nhập.")]
        [StringLength(30, ErrorMessage = "Tên đăng nhập được phép nhập tối đa 30 kí tự.")]
        public string TenDangNhap { get; set; }
        [Required(ErrorMessage = "Nhập mật khẩu.")]
        [StringLength(20, ErrorMessage = "Mật khẩu được phép nhập tối đa 20 kí tự.")]
        public string MatKhau { get; set; }
        public string MaLoaiKH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonBan> HoaDonBans { get; set; }
        public virtual LoaiKhachHang LoaiKhachHang { get; set; }
    }
}
