//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanDongHo60135761.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.HoaDonBans = new HashSet<HoaDonBan>();
        }
        [Required(ErrorMessage = "Nhập mã nhân viên.")]
        public string MaNV { get; set; }
        [Required(ErrorMessage = "Nhập họ tên nhân viên.")]
        public string HoTenNV { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime NgayLamViec { get; set; }
        public bool GioiTinhNV { get; set; }
        [Required(ErrorMessage = "Nhập số điện thoại nhân viên.")]
        [MinLength(10, ErrorMessage = "Nhập số điện thoại gồm 10 chữ số.")]
        public string SDTNV { get; set; }
        [Required(ErrorMessage = "Nhập địa chỉ nhân viên.")]
        public string DiaChiNV { get; set; }
        public string AnhNV { get; set; }
        [Required(ErrorMessage = "Nhập lương nhân viên.")]
        [Range(3000000, Int32.MaxValue, ErrorMessage = "Lương nhân viên ít nhất là {1:#,##0} đồng")]
        [DisplayFormat(DataFormatString = "{0:#,##0 đồng}", ApplyFormatInEditMode = false)]
        public int Luong { get; set; }
        [Required(ErrorMessage = "Nhập email nhân viên.")]
        [DataType(DataType.EmailAddress,ErrorMessage ="Nhập đúng định dạng email.")]
        [StringLength(30,ErrorMessage ="Email được phép nhập tối đa 30 kí tự.")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Nhập mật khẩu nhân viên.")]
        [StringLength(20, ErrorMessage = "Mật khẩu được phép nhập tối đa 20 kí tự.")]
        public string MatKhau { get; set; }
        public Nullable<int> MaQuyenDangNhap { get; set; }
        public string MaChucVu { get; set; }
    
        public virtual ChucVu ChucVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonBan> HoaDonBans { get; set; }
        public virtual QuyenDangNhapNhanVien QuyenDangNhapNhanVien { get; set; }
    }
}
